### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by ManiMozaffar** [ManiMozaffar/fast-auth#1]
Roadmap for developing boilerplate:

- [ ] Add email field
- [ ] Mail client
- [ ] Email and verify email address on registration endpoint
- [ ] Alarm unauthorized logins with mailing
- [ ] Change username/email/password functionality with 2FA step (as email/gauth)
- [ ] Opentelemetry integration
- [ ] OAuth2 proto integration
- [ ] OAuth support for gmail and apple

Roadmap for testıngs:
- [ ] Json data containing few user to be used in tests/dev stage to be injected to db directly
- [ ] Mocking email client
- [ ] Tests for all new features added
